// DO NOT EDIT THIS FILE - it is machine generated
#ifndef SPL_JNIFunctions_com_ibm_streamsx_sparkmllib_utils_h
#define SPL_JNIFunctions_com_ibm_streamsx_sparkmllib_utils_h

#include <SPL/Runtime/Function/SPLJavaFunction.h>
#include <SPL/Runtime/Type/SPLType.h>

namespace SPL {
namespace JNIFunctions {
namespace com {
namespace ibm {
namespace streamsx {
namespace sparkmllib {
namespace utils {
class SPL_JNIFunctions {
public:

// Generated from com.ibm.streamsx.sparkmllib.utils.Util in lib/streams-sparkmllib.jar at Sun Nov 05 09:46:13 EST 2017
static SPL::list<float64> getFeatureVector(SPL::ustring const & arg1) {
    static __thread void *func;
    static __thread jclass classGlobalRef;
    static __thread jmethodID mid;
    if (func == NULL) {
        func = SPL::SPLJavaFunction::loadFunction("com.ibm.streamsx.sparkmllib", "1.1.2.__dev__", SPLJAVAFUNCTION_ADL_FILENAME, "lib/streams-sparkmllib.jar", "com.ibm.streamsx.sparkmllib.utils.Util", "getFeatureVector", "(Ljava/lang/String;)[D", "com.ibm.streamsx.sparkmllib.utils", "<string T> public list<float64> getFeatureVector(T textData)", &classGlobalRef, &mid);
    }
    JNIEnv* env = SPL::SPLJavaFunction::getJNIEnv(func);
    jstring obj1 = env->NewString((jchar *) arg1.getBuffer(), (jsize) arg1.length());
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCreateError(func);
    jdoubleArray resObj = (jdoubleArray) env->CallStaticObjectMethod(classGlobalRef, mid, obj1);
    if (env->ExceptionCheck())
        SPL::SPLJavaFunction::throwCallError(func);
    env->DeleteLocalRef(obj1);
    if (resObj != NULL) {
        jdouble *elems = env->GetDoubleArrayElements(resObj, NULL);
        if (elems == NULL)
            SPL::SPLJavaFunction::throwCreateError(func);
        SPL::list<float64> result(elems, elems + env->GetArrayLength(resObj));
        env->ReleaseDoubleArrayElements(resObj, elems, JNI_ABORT);
        env->DeleteLocalRef(resObj);
        return result;
    } else {
        return SPL::list<float64>();
    }
}

// Generated from com.ibm.streamsx.sparkmllib.utils.Util in lib/streams-sparkmllib.jar at Sun Nov 05 09:46:13 EST 2017
static SPL::list<float64> getFeatureVector(SPL::rstring const & arg1) {
    SPL::list<float64> result = getFeatureVector(SPL::ustring::fromUTF8(arg1));
    return result;
}

// Generated from com.ibm.streamsx.sparkmllib.utils.Util in lib/streams-sparkmllib.jar at Sun Nov 05 09:46:13 EST 2017
template <SPL::int32 msize>
static SPL::list<float64> getFeatureVector(SPL::bstring<msize> const & arg1) {
    SPL::list<float64> result = getFeatureVector((SPL::rstring) arg1);
    return result;
}

};
}
}
}
}
}
}
}
#endif
